/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Main {

    public int[] roll(int n){
        if(n<0){n= 0;}

        int[] outputArray = new int[n];
        Random random = new Random();

        for (int i= 0; i < n ; i++){
            int randBetween1and6 = random.nextInt(6)+1;
            outputArray[i]=randBetween1and6;
        }
        return outputArray;
    }

    public boolean containsDuplicates (int[] arr){
        Set<Integer> set = new HashSet<Integer>();
        for ( int i = 0; i < arr.length; ++i ) {
            if ( set.contains( arr[i])) {
                return true;
            }
            else {
                set.add(arr[i]);
            }
        }
        return false;
    }

    public  double getAvg(int[] arr){
        if(arr.length==0) return 0;
        if(arr.length ==1) return arr[0];
        double sum=0;
        double avg =0;
        int size = arr.length;
        for (int x:arr){
            sum+=x;
        }
        avg = sum/size;
        return avg;
    }

    public int[] lowestAvg(int[][]arr){
        double currentAvg=0;
        double lowAvg=0;
        int numberOfLowestArray=0;

        lowAvg = getAvg(arr[0]);

        for(int i =1 ; i< arr.length; i++){

            currentAvg= getAvg(arr[i]);
            if(lowAvg>currentAvg){
                lowAvg=currentAvg;
                numberOfLowestArray=i;
            }

        }
        return arr[numberOfLowestArray];
    }


    public String analyzeWeather(int[][] arr){
        Set<Integer> uniqueTemperatures = new HashSet<>();
        int high = 0;
        int low = arr[0][0];
        String output = "";
        for(int[] innerArr : arr){
            for(int x : innerArr){
                uniqueTemperatures.add(x);
                if(x > high)
                    high = x;
                if(x < low)
                    low = x;
            }
        }
        output += "High: "+high+"\nLow: "+low;
        for(int i = low; i<=high; i++){
            if(! uniqueTemperatures.contains(i))
                output+="\nNever saw temperature: "+i;

        }
        return output;
    }

    public String tally(List<String> inputList){
        Map<String,Integer> votes = new HashMap<>();
        for(String item : inputList){
            votes.put(item,votes.getOrDefault(item,0)+1);
        }
        int maxVotes = 0 ;
        String winner="";
        for(String key: votes.keySet()){
            int currentVotes = votes.get(key);
            if(currentVotes > maxVotes){
                maxVotes = currentVotes;
                winner = key;
            }
        }

        return winner;
    }


}