/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;


import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    App tester = new App();

    @Test
    public void testLintMethod() {

        //file with errors
        String output = tester.reading("jsFileError.js");
        String expected = "Line 2: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 6: Missing semicolon.\n" +
                "Line 24: Missing semicolon.\n";
        assertEquals("must be " + expected, expected, output);

        //file with no errors
        output = tester.reading("jsFile.js");
        expected = "";
        assertEquals("must be no output", expected, output);

        // an empty file
        output = tester.reading("jsFileEmpty.js");
        expected = "";
        assertEquals("must be no output", expected, output);
    }
}